# Generated by Django 4.2.7 on 2023-11-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Įveskite užsakovo vardą ir pavardę', max_length=80, verbose_name='Vardas_pavarde')),
                ('email', models.CharField(help_text='Įveskite el. paštą', max_length=100, verbose_name='El.Paštas')),
                ('location', models.CharField(help_text='Įveskite adresą', max_length=100, verbose_name='Adresas')),
                ('phone_number', models.CharField(help_text='Įveskite Tel.Nr.', max_length=25, verbose_name='Tel.Nr')),
            ],
            options={
                'verbose_name': 'Užsakovas',
                'verbose_name_plural': 'Užsakovai',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Įveskite vairuotojo vardą ir pavardę', max_length=80, verbose_name='Vardas_pavarde')),
                ('driver_number', models.CharField(help_text='Įveskite darbuotojo numerį', max_length=20, verbose_name='Darbuotojo numeris')),
                ('phone_number', models.CharField(help_text='Įveskite Tel.Nr.', max_length=25, verbose_name='Tel.Nr')),
                ('email', models.CharField(help_text='Įveskite el. paštą', max_length=100, verbose_name='El.Paštas')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('a', 'Administruojama'), ('v', 'Vykdomas'), ('b', 'Baigtas'), ('a', 'Atšauktas')], default='a', help_text='Statusas', max_length=1)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.customer')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Įveskite produkto pavadinimą', max_length=50, verbose_name='Produktas')),
                ('unit_price', models.FloatField(help_text='Įveskite vieneto kainą', verbose_name='Vieneto kaina')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Įveskite transporto priemonės tipą', max_length=80, verbose_name='Transporto tipas')),
                ('plate_number', models.CharField(help_text='Įveskite valstybinį numerį', max_length=20, verbose_name='Valstybinis nr.')),
                ('status', models.CharField(blank=True, choices=[('a', 'Administruojama'), ('l', 'Laisva'), ('u', 'Užimta')], default='a', help_text='Statusas', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Įveskite sandėlio pavadinimą', max_length=50, verbose_name='Sandelys')),
                ('location', models.CharField(help_text='Įveskite sandėlio lokaciją', max_length=100, verbose_name='Lokacija')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateField(help_text='Įveskite išvykimo datą')),
                ('arrival', models.DateField(help_text='Įveskite atvykimo datą')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.order')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.warehouse'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicle'),
        ),
    ]
