# Generated by Django 4.2.7 on 2023-11-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Įveskite produkto kiekį', verbose_name='Kiekis'),
        ),
    ]
