# Generated by Django 4.2.7 on 2023-11-30 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_remove_product_quantity_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.customer'),
        ),
        migrations.AddField(
            model_name='route',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.warehouse'),
        ),
    ]
