# Generated by Django 4.2.7 on 2023-11-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_route_customer_route_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='customer',
        ),
    ]
