# Generated by Django 4.2.7 on 2023-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_remove_route_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(help_text='Įveskite el. paštą', max_length=100, unique=True, verbose_name='El.Paštas'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.CharField(help_text='Įveskite el. paštą', max_length=100, unique=True, verbose_name='El.Paštas'),
        ),
    ]
