# Generated by Django 4.2.7 on 2023-12-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_customer_name_alter_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, help_text='Įveskite transporto priemonės gamintoją', max_length=50, null=True, verbose_name='Gamintojas'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, help_text='Įveskite transporto priemonės modelį', max_length=50, null=True, verbose_name='Modelis'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Įveskite transporto priemonės gamybos metus', null=True, verbose_name='Metai'),
        ),
    ]
