# Generated by Django 4.2.7 on 2023-12-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_vehicle_make_vehicle_model_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Administruojama'), ('v', 'Vykdomas'), ('b', 'Baigtas'), ('c', 'Atšauktas')], default='a', help_text='Statusas', max_length=1),
        ),
    ]
