# Generated by Django 4.2.7 on 2023-12-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_foto',
            new_name='foto',
        ),
    ]
