# Generated by Django 4.2.7 on 2023-12-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_rename_user_foto_profile_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='foto',
            new_name='nuotrauka',
        ),
    ]
