# Generated by Django 4.2.7 on 2023-12-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_remove_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.customer'),
        ),
    ]
