# Generated by Django 4.2.7 on 2023-12-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_profile_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='customer',
        ),
    ]
